/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f407xx.h>
#include <stdio.h>
#include <string.h>

void delay()
{
	for(uint32_t i=0; i<500000; i++);
}

void delay2()
{
	for(uint32_t i=0; i<500000/2; i++);
}

#define HIGH 1
#define BTN_PRSSD HIGH

int main(void)
{
	GPIO_Handle_t GpioLed, GpioBtn;

	//copia o valor do meio em todas as entradas do espaço de memória passado, no caso, o GpioLed.
	//É uma boa prática fazer isso, porque a variável inicia sem lixo da memória
	memset(&GpioLed, 0, sizeof(GpioLed));
	memset(&GpioBtn, 0, sizeof(GpioBtn));

	GpioLed.pGPIOx = GPIOD;                                      //GPIOD
	GpioLed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_12;         //GPIOD12
	GpioLed.GPIO_PinConfig.GPIO_PinMode =   GPIO_MODE_OUT;       //OUTPUT
	GpioLed.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;      //Fast Transition between Low and High
	GpioLed.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;     //Output with Push Pull
	GpioLed.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PU_PD;  //Without PullUp or PullDown

	PeriClockControl(GPIOD, ENABLE); //faz um enable do clock daquele GPIO (basicamente um enable do barramento de clock (RCC) desse GPIO)
	GPIO_Init(&GpioLed);

	GpioBtn.pGPIOx = GPIOA;                                        //GPIOA0 - já está ligado ao botao na placa discovery, o botão está com um pino no VCC e no outro um resistor de PullDown
	GpioBtn.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_0;            //O mesmo ponto do resistor de PullDown está ligado ao GPIOA0 por um resistor.
	GpioBtn.GPIO_PinConfig.GPIO_PinMode =   GPIO_MODE_IN;          //INPUT
	GpioBtn.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;        //Fast Transition between Low and High
	//GpioBtn.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;     //Output with Push Pull - nessse caso é irrelevante pois é uma entrada
	GpioBtn.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PU_PD;    //Without PullUp or PullDown

	PeriClockControl(GPIOA, ENABLE); //faz um enable do clock daquele GPIO (basicamente um enable do barramento de clock (RCC) desse GPIO)
	GPIO_Init(&GpioBtn);

	while(1){
		if(ReadFromInputPin(GPIOA, GPIO_PIN_0) == BTN_PRSSD){
			delay2(); //para debouncing
			ToggleOutputPin(GPIOD, GPIO_PIN_12);
		}
	}

    return 0;
}

//Se a interrupção foi confugurada corretamente para o EXTIO0 o processador irá localizar a
//função abaixo
void EXTI0_IRQHandler(void)
{
	//Handle the interruption - Primeiramente a função abaixo irá limpar os registradores de interrupção
	//para ela não ficar infinitamente ativa (o que travaria o código)
	GPIO_IRQHandler(0);

	//A partir daqui escreva o código que rodará assim que a interrupção for detectada
}








